<?php while($donnees = $req->fetch()):?>

<div class="container">
  <div class="row">
    <div class=" col-md-6 col-md-push-3">
<!-- Article type-->
    <div class="panel panel-default">

      <div class="panel-heading panel-primary">
        <h3 class="panel-title"><?= '#' . $donnees['id'] . ' ' . htmlspecialchars($donnees['titre']);?></h3>
      </div>

      <div class="panel-body">
        <p><?= htmlspecialchars(substr($donnees['contenu'], 0, 15));?>   <a href="article.php?id=<?= $donnees['id']?>">[...]</a></p>
        <p>Auteur : <?= htmlspecialchars($donnees['nom']); ?></p>
      </div>

      <div class="panel-footer">
        <span><?= htmlspecialchars($donnees['dob']);?></span>
        <a href="article.php?id=<?= $donnees['id']?>">Voir l'article</a>
        <span class="pull-right">Catégorie :<?= htmlspecialchars($donnees['categorie']);?></span>
      </div>
    </div>

    </div>
  </div>
</div>

<?php endwhile;
$req->closeCursor();
?>
