<div class="container">
  <div class="row">
    <div class=" col-md-6 col-md-push-3">
<!-- Article type-->
    <div class="panel panel-primary">
      <div class="panel-heading panel-primary">
        <h3 class="panel-title"><?= '#' . $donnees['id'] . ' ' . htmlspecialchars($donnees['titre']);?></h3>
      </div>
      <div class="panel-body">
        <p><?= htmlspecialchars($donnees['contenu']);?></p>
        <p>Auteur : <?= htmlspecialchars($donnees['nom']); ?></p>
      </div>
      <div class="panel-footer">
        <span><?= htmlspecialchars($donnees['dob']);?></span>
        <a href="add_comment.php?id=<?= $donnees['id']?>">Ajouter commentaire</a>
        <span class="pull-right">Catégorie :<?= htmlspecialchars($donnees['categorie']);?></span>
      </div>
    </div>

    </div>
  </div>

<?php


foreach ($comment as $value) :?>

  <div class="row">
    <div class="col-md-5 col-md-push-4">

      <div class="panel panel-default">
        <div class="panel-heading panel-primary">
          <h3 class="panel-title"><strong>Auteur du com : </strong><?= htmlspecialchars($value['pseudo']);?></h3>
        </div>
        <div class="panel-body">
          <p><?= htmlspecialchars($value['content']);?></p>
        </div>
      </div>

    </div>
  </div>

<?php endforeach; ?>
</div>
