<div id="slider" class="slider">

  <?php foreach ($lastDrawings as $drawing):?>
    <img src="<?= $drawing ?>">
  <?php endforeach;?>

</div>

<?php foreach($posts as $post):?>
<div class="panel panel-info">
  <div class="panel-heading">
    <a href="<?= url('post/' . $post->getId()) ?>"><strong><?= htmlspecialchars($post->getTitle()) ?></strong></a>
    <span>le 
      <?= htmlspecialchars($post->getCreated_at()) ?>
      <em><?= htmlspecialchars($post->getContent()) ?></em>, par 
      <?= htmlspecialchars($post->getAuthor()->getName()) ?>
      <?php if($post->isAuthor()):?>
        <form method="post" action="<?= url('post/' . htmlspecialchars($post->getId()) . '/delete') ?>" class="pull-right">
          <button type="submit"><i class="fa fa-trash" aria-hidden="true"></i></button>
        </form>
        <form method="post" action="<?= url('post/' . htmlspecialchars($post->getId()) . '/edit') ?>" class="pull-right">
          <button type="submit"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></button>
        </form>
      <?php endif;?>
    </span>
  </div>
  <div class="panel-body">
    <img src="<?= htmlspecialchars($post->getDrawing_src())?>">
  </div>
</div>
<?php endforeach; ?>
