
    <?php if(!empty($errors)):?>

        <div class="panel panel-danger">
            <div class="panel-body">
            <?php foreach($errors as $value):?>
                <p><?= $value?></p>
            <?php endforeach; ?>
            </div>
        </div>
    <?php endif;?>

    <form method="post">
    
        <div class="form-group">
            <label for="name">Nom d'utilisateur :</label>
            <input type="text" class="form-control" id="name" name="name" placeholder="Nom d'utilisateur">
        </div>

        <div class="form-group">
            <label for="password">Password :</label>
            <input type="password" class="form-control" id="password" name="password" placeholder="Password">
        </div>

        <button type="submit" class="btn btn-default">Envoyer</button>
    </form>
