
    <?php if(!empty($errors)):?>

      <div class="panel panel-danger">
        <div class="panel-body">
          <?php foreach($errors as $value):?>
            <p><?= $value?></p>
          <?php endforeach; ?>
        </div>
      </div>
    <?php endif;?>

    <form method="post">
      <div class="form-group">
        <label for="name">Nom d'utilisateur :</label>
        <input type="text" class="form-control" id="name" name="name" placeholder="Nom d'utilisateur">
      </div>
      <div class="form-group">
        <label for="email">Email :</label>
        <input type="email" class="form-control" id="email" name="email" placeholder="Email">
      </div>
      <div class="form-group">
        <label for="password">Password :</label>
        <input type="password" class="form-control" id="password" name="password" placeholder="Password">
      </div>
      <div class="form-inline">
        <label for="birthday">Date de Naissance : </label>
        <select class="form-control" name="day">
          <?php for ($i = 1; $i <= 31; $i++): ?>
            <option><?= $i ?></option>
          <?php endfor; ?>
        </select>
        <select class="form-control" name="month">
          <?php $annee = ['Janvier', 'Février', 'Mars', 'Avril', 'Mai', 'Juin', 'Juillet', 'Août', 'Septembre', 'Octobre', 'Novembre', 'Décembre']?>
          <?php foreach ($annee as $value):?>
            <option><?= $value ?></option>
          <?php endforeach; ?>
        </select>
        <select class="form-control" name="year">
          <?php for ($i = 1960; $i <= 2017; $i++): ?>
            <option><?= $i ?></option>
          <?php endfor; ?>
        </select>
      </div>

      <button type="submit" class="btn btn-default">Envoyer</button>
    </form>

