<!-- ressources/views/layout.phtml -->
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><?= htmlentities($title) ?></title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="<?= url('ressources/css/slate.css')?>">
    <link rel="stylesheet" href="<?= url('ressources/css/slider.css')?>">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.2/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>



    <header class="container">
      <div class="row">
        <div class="pull-right">
          <?php if (!isLogged()):?>
            <ol class="breadcrumb">
              <li><a href="<?= url('login')?>">Connexion</a></li>
              <li><a href="<?= url('register')?>">Inscription</a></li>
            </ol>
          <?php else: ?>
            <ol class="breadcrumb">
              <li><a href="<?= url('user/' . $_SESSION['userId'])?>"><?= $_SESSION['userName'] ?></a></li>
              <li><a href="<?= url('signout')?>">Déconnexion</a></li>
            </ol>
          <?php endif; ?>
        </div>
        <div class="col-md-8 col-md-push-2">
          <a href="<?= url('pages/home')?>"><h1 class="text-center">Drawer</h1></a>
          <a href="<?= url('posts/create')?>"><h2 class="text-center">Dessiner</h2></a>
        </div>
      </div>
    </header>

    <div class="container">
    
      <div class="row">
        <main class="col-md-8 col-md-push-2">

          <h2 class="text-center"><?= htmlentities($title) ?></h2>
          <!--Pas besoin de __DIR__, PHP mémorise le chemin initial lorsqe l'on en est à la deuxième inclusion-->
          <?php include($template.'.phtml') ?>

        </main>
      </div>

    </div>

    <!-- Le pied de page -->
    <footer>Copyright</footer>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <script src="<?= url('ressources/js/slate/Pen.class.js')?>"></script>
    <script src="<?= url('ressources/js/slate/Slate.class.js')?>"></script>
    <script src="<?= url('ressources/js/slate/Tools.class.js')?>"></script>
    <script src="<?= url('ressources/js/utilities.js')?>"></script>
    <script src="<?= url('ressources/js/slider.js')?>"></script>
    <script src="<?= url('ressources/js/main.js')?>"></script>
  </body>
</html>
