<!-- ressources/views/layout.phtml -->
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title><?= htmlentities($title) ?></title>
    </head>

    <body>

    <!-- L'en-tête -->
    <header>
        <h1>Site Awesome!</h1>
    </header>

    <main>

        <h2><?= htmlentities($title) ?></h2>
        <!--Pas besoin de __DIR__, PHP mémorise le chemin initial lorsqe l'on en est à la deuxième inclusion-->
        <?php include($template.'.phtml') ?>

    </main>

    <!-- Le pied de page -->
    <footer>Copyright</footer>

    </body>
</html>
