    <?php if(!empty($errors)):?>

      <div class="panel panel-danger">
        <div class="panel-body">
          <?php foreach($errors as $value):?>
            <p><?= $value?></p>
          <?php endforeach; ?>
        </div>
      </div>
    <?php endif;?>



<div class="panel panel-default">
  <div class="panel-body">
    <form method="post">
        <div class="form-group">
            <label for="name">Votre Pseudo</label>
            <input type="text" class="form-control" name="name" id="name" placeholder="pseudo" value="<?= $this->getUser()->getName() ?>">
        </div>

        <div class="form-group">
            <label for="email">Votre Mail</label>
            <input type="email" class="form-control" name="email" id="email" placeholder="mail" value="<?= $this->getUser()->getEmail() ?>">
        </div>

        <button type="submit" class="btn btn-default">Submit</button>
    </form>
  </div>
</div>


<div class="panel panel-default">
  <div class="panel-body">
    <form method="post">

        <div class="form-group">
            <label for="password">Ancien Password</label>
            <input type="password" class="form-control" name="password" id="password" placeholder="Ancien Password">
        </div>
        <div class="form-group">
            <label for="newpassword">Nouveau Password</label>
            <input type="password" class="form-control" name="newpassword" id="newpassword" placeholder="Nouveau Password">
        </div>
        <div class="form-group">
            <label for="confirmpassword">Confirmez nouveau password</label>
            <input type="password" class="form-control" name="confirmpassword" id="confirmpassword" placeholder="Confirmez Password">
        </div>

        <button type="submit" class="btn btn-default">Submit</button>
    </form>
  </div>
</div>





