<div class="row">
    <div class="col-md-5 col-md-push-4">

      <div class="panel panel-default">
        <div class="panel-heading panel-primary">
          <h3 class="panel-title"><strong>Auteur du com : </strong><?= htmlspecialchars($value['pseudo']);?></h3>
        </div>
        <div class="panel-body">
          <p><?= htmlspecialchars($value['content']);?></p>
        </div>
      </div>

    </div>
  </div>