<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="styles.css">
        <title>Mon super site</title>
    </head>

    <body>

    <!-- L'en-tête -->
    <?php include('header.php');?>

    <div class="row">

        <!-- Le menu -->
        <?php include('menu.php');?>

        <!-- Le corps -->
        <main class="col-md-8" id="corps">
            <?php include($template.'.phtml'); ?>
        </main>
    </div>

    <!-- Le pied de page -->
    <?php include('footer.php');?>

    </body>
</html>
